app/src/AppBundle/Entity/BirthdayTrait.php
<?php
/**
 * This file is part of the Juvem package.
 *
 * (c) Erik Theoboldt <erik@theoboldt.eu>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Entity;


trait BirthdayTrait
{
    /**
     * Birthday of person
     *
     * @var \DateTime
     */
    protected $birthday;
    
    /**
     * Set birthday
     *
     * @param \DateTime $birthday
     *
     * @return BirthdayTrait
     */
    public function setBirthday($birthday)
    {
        if ($birthday) {
            $birthday = clone $birthday;
            $birthday->setTime(10, 00);
        }
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * Get birthday
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        if ($this->birthday) {
            $this->birthday->setTime(10, 00);
        }
        return $this->birthday;
    }

    /**
     * Get age of participant at the related event
     *
     * @param int|null $precision If you want the result to be rounded with round(), specify precision here
     * @return float              Age in years
     */
    public function getAgeAtEvent($precision = null): ?float
    {
        $event          = $this->getEvent();
        $eventStartDate = $event->getStartDate();
        if (!$eventStartDate) {
            return null;
        }
        return EventRepository::age($this->getBirthday(), $event->getStartDate(), $precision);
    }

    /**
     * Get age of participant at the related event
     *
     * @return int|null Amount of years of life at event
     */
    public function getYearsOfLifeAtEvent(): ?int
    {
        $event          = $this->getEvent();
        $eventStartDate = $event->getStartDate();
        if (!$eventStartDate) {
            return null;
        }
        return EventRepository::yearsOfLife($this->getBirthday(), $eventStartDate);
    }

    /**
     * Check if participant has birthday at related event
     *
     * @return bool True if so
     */
    public function hasBirthdayAtEvent()
    {
        $event          = $this->getEvent();
        $eventStartDate = $event->getStartDate();
        if (!$eventStartDate) {
            return false;
        }
        return EventRepository::hasBirthdayInTimespan(
            $this->getBirthday(), $event->getStartDate(), $event->getEndDate()
        );
    }
    
    /**
     * Expected to have event assigned
     *
     * @return Event|null
     */
    abstract function getEvent(): ?Event;
}

app/src/AppBundle/Entity/Employee.php
<?php
/**
 * This file is part of the Juvem package.
 *
 * (c) Erik Theoboldt <erik@theoboldt.eu>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


namespace AppBundle\Entity;


use AppBundle\Entity\AcquisitionAttribute\Attribute;
use AppBundle\Entity\Audit\CreatedModifiedTrait;
use AppBundle\Entity\Audit\ProvidesCreatedInterface;
use AppBundle\Entity\Audit\ProvidesModifiedInterface;
use AppBundle\Entity\Audit\SoftDeleteableInterface;
use AppBundle\Entity\Audit\SoftDeleteTrait;
use AppBundle\Entity\ChangeTracking\SpecifiesChangeTrackingAttributeConvertersInterface;
use AppBundle\Entity\ChangeTracking\SpecifiesChangeTrackingComparableRepresentationInterface;
use AppBundle\Entity\ChangeTracking\SpecifiesChangeTrackingStorableRepresentationInterface;
use AppBundle\Entity\ChangeTracking\SupportsChangeTrackingInterface;
use AppBundle\Entity\CustomField\CustomFieldValueCollection;
use AppBundle\Entity\CustomField\CustomFieldValueTrait;
use AppBundle\Entity\CustomField\EntityHavingCustomFieldValueInterface;
use AppBundle\Manager\Geo\AddressAwareInterface;
use AppBundle\Manager\Payment\PriceSummand\SummandImpactedInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as Serialize;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @Serialize\ExclusionPolicy("all")
 * @Serialize\ReadOnlyProperty()
 * @ORM\Entity
 * @ORM\Table(name="employee")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass="AppBundle\Entity\EmployeeRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=true)
 */
class Employee implements EventRelatedEntity, EntityHavingCustomFieldValueInterface, EntityHavingPhoneNumbersInterface, SummandImpactedInterface, SoftDeleteableInterface, AddressAwareInterface, ProvidesModifiedInterface, ProvidesCreatedInterface, SupportsChangeTrackingInterface, SpecifiesChangeTrackingStorableRepresentationInterface, SpecifiesChangeTrackingComparableRepresentationInterface, SpecifiesChangeTrackingAttributeConvertersInterface, HumanInterface
{
    use HumanTrait, CreatedModifiedTrait, AddressTrait, CommentableTrait;
    use CustomFieldValueTrait;
    
    use SoftDeleteTrait {
        setDeletedAt as traitSetDeletedAt;
    }
    
    /**
     * @ORM\Column(type="integer", name="gid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $gid;
    
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Event", inversedBy="employees", cascade={"all"})
     * @ORM\JoinColumn(name="eid", referencedColumnName="eid", onDelete="cascade")
     *
     * @var Event
     */
    protected $event;
    
    /**
     * @ORM\Column(type="string", length=64, name="salutation")
     * @Assert\NotBlank()
     */
    protected $salutation;
    
    /**
     * @ORM\Column(type="string", length=128, name="email")
     * @Assert\NotBlank()
     */
    protected $email;
    
    /**
     * Contains the phone numbers assigned to this employee
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\PhoneNumber", cascade={"all"}, mappedBy="employee")
     */
    protected $phoneNumbers;
    
    /**
     * Contains the comments assigned
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\EmployeeComment", cascade={"all"}, mappedBy="employee")
     */
    protected $comments;

    /**
     * Custom field value collection containing a list of {@see CustomFieldValueContainer}
     *
     * Stores array or {@see CustomFieldValueCollection} which can be generated from this array containing a list
     * of {@see CustomFieldValueContainer} identified by the related {@see Attribute} id. Is encoded to JSON
     * when entity is persisted to database
     * 
     * @var CustomFieldValueCollection|array
     * @ORM\Column(type="json", length=16777215, name="custom_field_values", nullable=true)
     */
    private $customFieldValues = [];

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="assignedEmployees")
     * @ORM\JoinColumn(name="uid", referencedColumnName="uid", onDelete="SET NULL")
     */
    protected $assignedUser;
    
    /**
     * @ORM\ManyToOne(targetEntity="Employee")
     * @ORM\JoinColumn(name="predecessor_gid", referencedColumnName="gid", onDelete="SET NULL")
     * @var Employee|null
     */
    protected $predecessor = null;
    
    /**
     * @ORM\Column(type="boolean", name="is_confirmed")
     */
    protected $isConfirmed = false;
    
    /**
     * Employee constructor.
     *
     * @param Event|null $event Related event
     */
    public function __construct(Event $event = null)
    {
        $this->phoneNumbers = new ArrayCollection();
        $this->comments     = new ArrayCollection();
        $this->modifiedAt   = new \DateTime();
        $this->createdAt    = new \DateTime();
        $this->event        = $event;
    }
    
    /**
     * Get employee id
     *
     * @return int|null
     */
    public function getGid(): ?int
    {
        return $this->gid;
    }
    
    /**
     * {@inheritdoc}
     */
    public function getId(): ?int
    {
        return $this->getGid();
    }

    /**
     * @return mixed
     */
    public function getSalutation()
    {
        return $this->salutation;
    }

    /**
     * @param mixed $salutation
     */
    public function setSalutation($salutation): void
    {
        $this->salutation = $salutation;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     * @return Employee
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * Get phone Numbers
     *
     * @return array
     */
    public function getPhoneNumbers()
    {
        return $this->phoneNumbers->toArray();
    }

    /**
     * Add phoneNumber
     *
     * @param PhoneNumber $phoneNumber
     *
     * @return Employee
     */
    public function addPhoneNumber(PhoneNumber $phoneNumber)
    {
        if (!$this->phoneNumbers->contains($phoneNumber)) {
            $this->phoneNumbers->add($phoneNumber);
            $phoneNumber->setEmployee($this);
        }

        return $this;
    }

    /**
     * Remove phoneNumber
     *
     * @param PhoneNumber $phoneNumber
     * @return Employee
     */
    public function removePhoneNumber(PhoneNumber $phoneNumber)
    {
        $this->phoneNumbers->removeElement($phoneNumber);
        return $this;
    }

    /**
     * Get related event
     *
     * @return Event|null
     */
    public function getEvent(): ?Event
    {
        return $this->event;
    }

    /**
     * @param Event $event
     */
    public function setEvent(?Event $event): void
    {
        $this->event = $event;
    }

    /**
     * Set assignedUser
     *
     * @param User $assignedUser
     *
     * @return Employee
     */
    public function setAssignedUser(User $assignedUser = null)
    {
        $this->assignedUser = $assignedUser;

        return $this;
    }

    /**
     * Get assignedUser
     *
     * @return \AppBundle\Entity\User|null
     */
    public function getAssignedUser()
    {
        return $this->assignedUser;
    }
    
    /**
     * @return bool
     */
    public function hasPredecessor(): bool
    {
        return $this->predecessor !== null;
    }
    
    /**
     * @return null|Employee
     */
    public function getPredecessor(): ?Employee
    {
        return $this->predecessor;
    }
    
    /**
     * @param null|Employee $predecessor
     * @return Employee
     */
    public function setPredecessor(?Employee $predecessor)
    {
        $this->predecessor = $predecessor;
        return $this;
    }
    
    /**
     * @return bool
     */
    public function isConfirmed(): bool
    {
        return $this->isConfirmed;
    }

    /**
     * @param bool $isConfirmed
     */
    public function setIsConfirmed(bool $isConfirmed = true): void
    {
        $this->isConfirmed = $isConfirmed;
    }

    /**
     * Create a new employee for transmitted event based on data of given employee
     *
     * @param Employee $employeePrevious           Data template
     * @param Event    $event                      Event this new employee should belong to
     * @param bool     $copyPrivateFields          If set to true, also private acquisition data and user assignments
     *                                             are copied
     * @return Employee
     */
    public static function createFromTemplateForEvent(
        Employee $employeePrevious, Event $event, bool $copyPrivateFields = false
    )
    {
        /** @var Employee $employee */
        $employee = new self($event);
        $employee->setNameLast($employeePrevious->getNameLast());
        $employee->setNameFirst($employeePrevious->getNameFirst());
        $employee->setAddressCity($employeePrevious->getAddressCity());
        $employee->setAddressStreet($employeePrevious->getAddressStreet());
        $employee->setAddressZip($employeePrevious->getAddressZip());
        $employee->setAddressCountry($employeePrevious->getAddressCountry());
        $employee->setEmail($employeePrevious->getEmail());
        $employee->setSalutation($employeePrevious->getSalutation());
        $employee->setIsConfirmed(true);
        $employee->setPredecessor($employeePrevious);

        if ($copyPrivateFields) {
            $employee->setAssignedUser($employeePrevious->getAssignedUser());
        }

        /** @var PhoneNumber $numberPrevious */
        foreach ($employeePrevious->getPhoneNumbers() as $numberPrevious) {
            $number = new PhoneNumber();
            $number->setEmployee($employee);
            $number->setDescription($numberPrevious->getDescription());
            $number->setNumber($numberPrevious->getNumber());

app/src/AppBundle/Controller/Event/Participation/AdminAuditController.php
<?php
/**
 * This file is part of the Juvem package.
 *
 * (c) Erik Theoboldt <erik@theoboldt.eu>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Controller\Event\Participation;

use AppBundle\Audit\AuditProvider;
use AppBundle\Controller\AuthorizationAwareControllerTrait;
use AppBundle\Controller\FormAwareControllerTrait;
use AppBundle\Controller\RenderingControllerTrait;
use AppBundle\Entity\Event;
use AppBundle\Http\Annotation\CloseSessionEarly;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Twig\Environment;

class AdminAuditController
{
    use AuthorizationAwareControllerTrait, FormAwareControllerTrait, RenderingControllerTrait;

    private AuditProvider $auditProvider;

    /**
     * AdminSingleController constructor.
     *
     * @param Environment                   $twig
     * @param RouterInterface               $router
     * @param AuthorizationCheckerInterface $authorizationChecker
     * @param TokenStorageInterface         $tokenStorage
     * @param FormFactoryInterface          $formFactory
     */
    public function __construct(
        AuditProvider                 $auditProvider,
        Environment                   $twig,
        RouterInterface               $router,
        AuthorizationCheckerInterface $authorizationChecker,
        TokenStorageInterface         $tokenStorage,
        FormFactoryInterface          $formFactory
    ) {
        $this->auditProvider        = $auditProvider;
        $this->twig                 = $twig;
        $this->router               = $router;
        $this->authorizationChecker = $authorizationChecker;
        $this->tokenStorage         = $tokenStorage;
        $this->formFactory          = $formFactory;
    }


    /**
     * Present all changes happened to entities related to transmitted event
     *
     * @CloseSessionEarly
     * @ParamConverter("event", class="AppBundle:Event", options={"id" = "eid"})
     * @Route("/admin/event/{eid}/changes", requirements={"eid": "\d+"}, name="event_participants_changes")
     * @Security("is_granted('participants_read', event)")
     */
    public function showEventRelatedChangesAction(Event $event, Request $request)
    {
        $date = new \DateTimeImmutable('yesterday noon');
        $form = $this->createFormBuilder()
                     ->add(
                         'date',
                         DateType::class,
                         [
                             'label'  => 'Datum',
                             'years'  => range((int)Date('Y') - 1, (int)Date('Y') + 1),
                             'widget' => 'single_text',
                             'format' => 'yyyy-MM-dd',
                             'data'   => $date,
                         ]
                     )
                     ->getForm();
        $form->handleRequest($request);

        $auditEvents = [];

        if ($form->isSubmitted() && $form->isValid()) {
            $date = $form->get('date')->getData();
            if ($date instanceof \DateTime) {
                $date->setTime(0, 0, 0);
            } elseif ($date instanceof \DateTimeImmutable) {
                $date = $date->setTime(0, 0, 0);
            }

            if ($date) {
                $auditEvents = $this->auditProvider->provideAuditEvents($event, $date);
            }
        }
        return $this->render(
            'event/admin/track-changes.html.twig',
            [
                'event'       => $event,
                'date'        => $date,
                'auditEvents' => $auditEvents,
                'form'        => $form->createView(),
            ]
        );
    }
}

app/templates/event/participation/admin/embed-detail-participant.html.twig
<div class="col-xs-12">
    <dl class="dl-horizontal">
        <dt>Vorname</dt>
        <dd>{{ participant.nameFirst }}</dd>
        <dt>Nachname</dt>
        <dd>{{ participant.nameLast }}</dd>
        <dt>Geschlecht</dt>
        <dd>{{ participant.getGender() }}</dd>
        <dt>Geburtsdatum</dt>
        <dd>
            {{ participant.getBirthday|date("d.m.Y") }}
            {% if (participant.hasBirthdayAtEvent) %}
                {{ 'gift'|glyph(participant.nameFirst ~ ' hat während der Veranstaltung Geburtstag') }}
            {% endif %}
        </dd>
        <dt>Alter</dt>
        <dd><span data-toggle="tooltip" title="{{ participant.nameFirst }} hat zu Beginn der Veranstaltung das {{ participant.yearsOfLifeAtEvent }}.&nbsp;Lebensjahr erreicht">{{ participant.yearsOfLifeAtEvent }} Jahre</span> (rund {{ participant.getAgeAtEvent|number_format(1) }} Jahre)
        </dd>
        <dt>Medizinische Hinweise</dt>
        <dd>
            {% if participant.infoMedical %}
                {{ participant.infoMedical }}
            {% else %}
                <i class="empty no-special"><span></span></i>
            {% endif %}
        </dd>
        <dt>Allgemeine Hinweise</dt>
        <dd>
            {% if participant.infoGeneral %}
                {{ participant.infoGeneral }}
            {% else %}
                <i class="empty no-special"><span></span></i>
            {% endif %}
        </dd>
        {% for customField in event.getAcquisitionAttributes(false, true, false, true, true) %}
            <dt {% if customField.formDescription != customField.managementTitle %} title="{{ customField.formDescription }}" data-toggle="tooltip" data-placement="right"{% endif %}>
                {%- if not customField.isPublic -%}
                    {{ 'lock'|glyph('Dieses Feld wird nur intern und nicht in der öffentlichen Anmeldung angezeigt') }}
                {% endif %}
                {%- if customField.isDeleted -%}
                    {{ 'trash'|glyph('Dieses Feld ist im Papierkorb') }}
                {% endif %}
                {%- if customField.isArchived -%}
                    {{ 'folder-close'|glyph('Dieses ist archiviert') }}
                {% endif %}
                {{ customField.managementTitle }}
            </dt>
            <dd>
                {% set customFieldValueContainer = participant.customFieldValues.get(customField.id) %}
                {% if customFieldValueContainer %}
                    {{ customFieldValueContainer|customFieldValue(participant, true) }}
                {% else %}
                    <i class="empty value-not-specified"><span></span></i>
                {% endif %}
            </dd>
        {% endfor %}
        {% if paymentManager and event.price %}
            <dt>Preis</dt>
            <dd>
                <span id="participant-price-{{ participant.aid }}">
                    {{ paymentManager.getParticipantPaymentStatus(participant)|paymentInfo }}
                </span>
                {% if is_granted('participants_edit', event) -%}
                    <button data-toggle="modal"
                            data-target="#dialogPriceConfiguration"
                            data-aids="{{ participant.aid }}"
                            data-title="{{ participant|fullname }}"
                            class="btn btn-default btn-xs"
                            title="Grundpreis festlegen/Zahlung erfassen">{{ 'credit-card'|glyph }}</button>
                {% endif -%}
            </dd>
        {% endif -%}
        <dt>Bestätgung</dt>
        <dd>
            {% if participant.confirmed %}bestätigt{%- endif -%}
            {%- if participant.confirmationSentAt -%}
                {% if not participant.confirmed %}momentan unbestätigt, zwischenzeitlich{% else %}, {% endif %}
                <span data-toggle="tooltip" data-placement="top"
                      title="{% if participant.confirmationSentAt|date("U") != "946717200" %}Benachrichtigung versandt am {{ participant.confirmationSentAt|date("d.m.Y H:i") }}{% else %}Zeitpunkt der Benachrichtigung unbekannt{% endif %}"
                >benachrichtigt</span>
            {% else %}
                unbestätigt
            {% endif %}
        </dd>
        <dt>Letzte Änderung</dt>
        <dd>
            {%- if participant.createdAt.format('U') == participant.modifiedAt.format('U') -%}
                <i data-toggle="tooltip" data-placement="bottom"
                   title="{{ participant.modifiedAt|date("d.m.Y H:i:s") }}">
                    (keine)
                </i>
            {%- else -%}
                {{ participant.modifiedAt|date("d.m.Y H:i:s") }}
            {%- endif -%}
        </dd>
    {% if similarParticipants -%}
        <dt>Weitere Teilnahmen</dt>
        <dd class="participant-additional-occurrences">
            {% if similarParticipants[participant.aid]|length == 0 %}
                <i>(keine Teilnahmen bei anderen Veranstaltungen)</i>
            {% endif %}
            {% for relatedParticipant in similarParticipants[participant.aid] %}
                <a class="{% if relatedParticipant.isDeleted %} participantdeleted{% endif %}{% if relatedParticipant.withdrawnOrRejected %} widthdrawnrejected{% endif %}{% if relatedParticipant.eventDeleted %} eventdeleted{% endif %}{% if relatedParticipant.confirmed %} confirmed{% endif %}"
                   data-toggle="tooltip"
                   title="Veranstaltung: {{ relatedParticipant.getEventDateFormatted() }}{% if relatedParticipant.eventDeleted %} (gelöscht){% endif %}, Angemeldet: {{ relatedParticipant.getCreatedDateFormatted() }}
{% if relatedParticipant.isDeleted %} (gelöscht){% endif %}{% if relatedParticipant.withdrawnOrRejected %} (zurückgezogen/abgelehnt){% endif %}{% if relatedParticipant.confirmed %}(bestätigt){% endif %}"
                   href="{{ path('event_participation_detail', {eid: relatedParticipant.eid, pid: relatedParticipant.pid}) }}">{{ relatedParticipant.getTitle() }}</a>{% if not loop.last and loop.length > 1 %}, {% endif %}
            {% endfor %}
        </dd>
        {% endif %}
    </dl>
</div>
<div class="col-xs-12 status-label-list">
    {{ ' '|bitmask(participant.getStatus(true), statusFormatter) }}
    {% if paymentManager -%}
        {{ paymentManager.getParticipantPaymentStatus(participant)|paymentLabel }}
    {%- endif %}
    {% if participant.isDeleted %}<span class="label label-danger">gelöscht</span>{% endif %}
</div>

app/templates/event/participation/admin/embed-detail-participation.html.twig
<div class="col-xs-12">
  <dl class="dl-horizontal">
    <dt>Anrede</dt>
    <dd>{{ participation.salutation }}</dd>
    <dt>Vorname</dt>
    <dd>{{ participation.nameFirst }}</dd>
    <dt>Nachname</dt>
    <dd>{{ participation.nameLast }}</dd>
    <dt>Telefon</dt>
    <dd class="phone-container">
      {% for phoneNumber in participation.phoneNumbers %}
        <div>
          <a href="tel:{{ phoneNumber.number|phone_number_format(constant('\\libphonenumber\\PhoneNumberFormat::INTERNATIONAL')) }}">{{ phoneNumber.number|phone_number_format(constant('\\libphonenumber\\PhoneNumberFormat::INTERNATIONAL')) }}</a>
          {% if phoneNumber.description %}
            <br>
            <i>{{ phoneNumber.description }}</i>
          {% endif %}
        </div>
      {% endfor %}

    </dd>
    <dt>Anschrift</dt>
    <dd class="address-container">
      <address>
        <strong>{{ participation.getName() }}</strong><br>
        {{ participation.addressStreet }}<br>
        {{ participation.addressZip }} {{ participation.addressCity }}{% if participation.addressCountry != constant('AppBundle\\Entity\\Event::DEFAULT_COUNTRY') %}
          <br>
          {{ participation.addressCountry }}{% endif %}
      </address>
    </dd>
    <dt>E-Mail Adresse</dt>
    <dd class="address-container">
      <address>
        <a href="mailto:{{ participation.email }}">{{ participation.email }}</a>
      </address>
    </dd>
    {% for customField in event.getAcquisitionAttributes(true, false, false, true, true) %}
        <dt {% if customField.formDescription != customField.managementTitle %} title="{{ customField.formDescription }}" data-toggle="tooltip" data-placement="right"{% endif %}>
            {%- if not customField.isPublic -%}
                {{ 'lock'|glyph('Dieses Feld wird nur intern und nicht in der öffentlichen Anmeldung angezeigt') }}
            {% endif %}
            {%- if customField.isDeleted -%}
                {{ 'trash'|glyph('Dieses Feld ist im Papierkorb') }}
            {% endif %}
            {%- if customField.isArchived -%}
                {{ 'folder-close'|glyph('Dieses ist archiviert') }}
            {% endif %}
            {{ customField.managementTitle }}
        </dt>
        <dd>
            {% set customFieldValueContainer = participation.customFieldValues.get(customField.id) %}
            {% if customFieldValueContainer %}
                {{ customFieldValueContainer|customFieldValue(participation, true) }}
            {% else %}
                <i class="empty value-not-specified"><span></span></i>
            {% endif %}
        </dd>
    {% endfor %}
    <dt title="Eingang der Anmeldung" data-toggle="tooltip" data-placement="right">Eingang</dt>
    <dd>{{ participation.createdAt|date("d.m.Y H:i") }}</dd>
    <dt>Letzte Änderung</dt>
    <dd>
      {%- if participation.createdAt.format('U') == participation.modifiedAt.format('U') -%}
        <i data-toggle="tooltip" data-placement="bottom" title="{{ participation.modifiedAt|date("d.m.Y H:i:s") }}">
          (keine)
        </i>
      {%- else -%}
        {{ participation.modifiedAt|date("d.m.Y") }}
        <span data-toggle="tooltip" data-placement="bottom" title="{{ participation.modifiedAt|date("H:i:s") }}">
          {{ participation.modifiedAt|date("H:i") }}
        </span>
      {%- endif -%}
    </dd>

    <dt title="Ist die Anmeldung mit einem Benutzerkonto verknüpft, ist dieses hier angegeben"
        data-toggle="tooltip" data-placement="right">
      Benutzerkonto
    </dt>
    <dd>
      {% if participation.assignedUser %}<a href="{{ path('user_detail', {'uid': participation.assignedUser.uid}) }}">
        {{ participation.assignedUser|fullname }}</a>
      {% else %}
        <i>(keines)</i>
      {% endif %}
      {% if is_granted('participants_edit', event) -%}
        <button data-toggle="modal" data-target="#dialogModalAssignUser"
                class="btn btn-default btn-xs"
                title="Benutzerkonto verknüpfen">{{ 'pencil'|glyph }}</button>
      {% endif -%}
    </dd>
  </dl>
</div>

app/templates/event/participation/admin/export.html.twig
{% extends 'base.html.twig' %}

{% block title %}Anmeldungen exportieren ({{ event.title }}){% endblock %}

{% block body %}
    {% embed 'common/header/base-page-header.html.twig' with {'title': 'Teilnehmer:innen', 'subtitle': 'exportieren'} %}
        {% block breadcrumb %}
            <li><a href="{{ path('event_list') }}">Veranstaltungen</a></li>
            <li><a href="{{ path('event', {'eid': event.eid }) }}">{{ event.title }}</a></li>
            <li><a href="{{ path('event_participants_list', {'eid': event.eid }) }}">Teilnehmer:innen</a></li>
            <li class="active">Teilnehmer:innen exportieren</li>
        {% endblock %}
    {% endembed %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">

            </div>
        </div>
    </div>
{% endblock %}

app/templates/event/participation/admin/partial-participant-detail.html.twig
<!DOCTYPE html>
<html lang="de">
<head>
</head>
<body>
<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">{{ 'file'|glyph }} Anmeldung</h3>
    </div>
    <div class="panel-body">
      {% include 'event/participation/admin/embed-detail-participation.html.twig' with {'participation': participation} %}
    </div>
  </div>
</div>


<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">{{ 'user'|glyph }} {{ participant.nameFirst }}</h3>
    </div>
    <div class="panel-body">
      {% include 'event/participation/admin/embed-detail-participant.html.twig' with {'participant': participant, 'event': event, 'paymentManager': paymentManager, 'similarParticipants': similarParticipants, enableEditMode: false} %}
    </div>
  </div>
</body>
</html>