app/src/AppBundle/Entity/CommentBase.php
<?php
/**
 * This file is part of the Juvem package.
 *
 * (c) Erik Theoboldt <erik@theoboldt.eu>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Entity;

use AppBundle\Entity\Audit\CreatorModifierTrait;
use AppBundle\Entity\Audit\CreatedModifiedTrait;
use AppBundle\Entity\Audit\ProvidesCreatedInterface;
use AppBundle\Entity\Audit\ProvidesCreatorInterface;
use AppBundle\Entity\Audit\ProvidesModifiedInterface;
use AppBundle\Entity\Audit\ProvidesModifierInterface;
use AppBundle\Entity\Audit\SoftDeleteableInterface;
use AppBundle\Entity\Audit\SoftDeleteTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation as Serialize;

/**
 * Class CommentBase
 *
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=true)
 *
 * @package AppBundle\Entity
 */
abstract class CommentBase implements SoftDeleteableInterface, ProvidesModifiedInterface, ProvidesCreatedInterface, ProvidesCreatorInterface, ProvidesModifierInterface
{
    use CreatedModifiedTrait, SoftDeleteTrait, CreatorModifierTrait;

    /**
     * @ORM\Column(type="integer", name="cid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $cid;

    /**
     * @ORM\Column(type="text", name="content")
     * @Assert\NotBlank()
     */
    protected $content;

    /**
     * Get cid
     *
     * @return integer
     */
    public function getCid()
    {
        return $this->cid;
    }

    /**
     * Set content
     *
     * @param string $content
     *
     * @return CommentBase
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Get class name
     *
     * @return string
     */
    public function getBaseClassName()
    {
        return get_class($this);
    }

    /**
     * Get id of related object
     *
     * @return integer
     */
    public abstract function getRelatedId();

    /**
     * Get related object
     *
     * @return object
     */
    public function getRelated()
    {
        if (preg_match('/(?:\\\\)*([^\\\\]+)Comment$/', $this->getBaseClassName(), $classData)) {
            $relatedAcessor = 'get'.$classData[1];
            try {
                $comment = new \ReflectionClass(get_class($this));
            } catch (\ReflectionException $e) {
                throw new \InvalidArgumentException('Unexpected class occurred');
            }
            if ($comment->hasMethod($relatedAcessor)) {
                return $this->$relatedAcessor();
            } else {
                throw new \InvalidArgumentException('Comment class has not expected accessor for related object');
            }
        } else {
            throw new \InvalidArgumentException('Comment class name is not as expected');
        }
    }
}

app/templates/common/active-button-content.html.twig
{% if buttonIsEnabled %}
    <span {% if buttons.buttonDisable.label is defined %}title="{{ buttons.buttonDisable.label}}"{% endif %}>
    {% if buttons.buttonDisable.glyph is defined %}
        {{ buttons.buttonDisable.glyph|glyph }}
    {% endif %}
    {% if buttons.buttonDisable.label is defined and not isXs %}
        <span class="hidden-xs">{{ buttons.buttonDisable.label}}</span>
    {% endif %}
    </span>
{% else %}
    <span {% if buttons.buttonEnable.label is defined %}title="{{ buttons.buttonEnable.label}}"{% endif %}>
    {% if buttons.buttonEnable.glyph is defined %}
        {{ buttons.buttonEnable.glyph|glyph }}
    {% endif %}
    {% if buttons.buttonEnable.label is defined and not isXs %}
        <span class="hidden-xs">{{ buttons.buttonEnable.label}}</span>
    {% endif %}
    </span>
{% endif %}

app/templates/common/active-button.html.twig
{% set buttonId = random() %}
<button type="button" class="btn btn-default" id="{{ buttonId }}">
    {% include 'common/active-button-content.html.twig' with {buttonIsEnabled: button.isEnabled, buttons: button.buttons} %}
    {% cspscript %}
    <script type='text/javascript'>
        $(function () {
            $('#{{ buttonId }}').click(function () {
                var button = $('#{{ buttonId }}');

                $(button).prop('disabled', true);
                $.ajax({
                    type: 'POST',
                    url: '{{ path('active_button') }}',
                    data: {
                        _token: '{{ csrf_token(button.entityName ~ button.propertyName ) }}',
                        entityName: '{{ button.entityName }}',
                        entityId: '{{ button.entityId }}',
                        propertyName: '{{ button.propertyName }}',
                        toggle: 1,
                        buttons: {
                            buttonEnable: {
                                label: '{{ button.buttons.buttonEnable.label }}',
                                glyph: '{{ button.buttons.buttonEnable.glyph }}'
                            },
                            buttonDisable: {
                                label: '{{ button.buttons.buttonDisable.label }}',
                                glyph: '{{ button.buttons.buttonDisable .glyph }}'
                            }

                        }
                    },
                    datatype: 'json',
                    success: function (response) {
                        button.empty();
                        if (response && response.html) {
                            button.html(response.html);
                        }
                        {% block success %}{% endblock %}
                    },
                    error: function (response) {
                        $(document).trigger('add-alerts', {
                            message: 'Die gewünschte Aktion wurde nicht korrekt ausgeführt',
                            priority: 'error'
                        });
                        {% block error %}{% endblock %}
                    },
                    complete: function (response) {
                        button.prop('disabled', false);
                        {% block complete %}{% endblock %}
                    }
                });
            });
        });
    </script>
    {% endcspscript %}
</button>

app/templates/common/comment-content.html.twig
<div class="comment" data-cid="{{ comment.cid }}">
    <div class="content">
        {{ comment.content|markdown_shifted }}
    </div>
    <p class="meta">
        <small>
            <a href="{{ path('user_detail', {uid: comment.createdBy.uid}) }}">{{ comment.createdBy|fullname }}</a>
            <span title="{{ comment.createdAt|date("d.m.Y h:i") }}"
                  data-toggle="tooltip">{{ comment.createdAt|ago }}</span>{% if comment.modifiedAt %},
            geändert von <a
                href="{{ path('user_detail', {uid: comment.modifiedBy.uid}) }}">{{ comment.modifiedBy|fullname }}</a>
            <span title="{{ comment.modifiedAt|date("d.m.Y h:i") }}"
                  data-toggle="tooltip">{{ comment.modifiedAt|ago }}</span>{% endif %}{% if comment.isDeleted %},
                gelöscht <span title="{{ comment.deletedAt|date("d.m.Y h:i") }}"
                               data-toggle="tooltip">{{ comment.deletedAt|ago }}</span>
            {% endif %}
        </small>
        {% if app.user == comment.createdBy %}
            <button class="btn btn-xs btn-default btn-edit-comment" title="Kommentar bearbeiten" data-toggle="modal"
                    data-target="#dialogModalComment" data-cid="{{ comment.cid }}" data-content="{{ comment.content }}"
                    data-comment-class="{{ comment.baseClassName }}"
                    data-related-id="{{ comment.relatedId }}">{{ 'pencil'|glyph }}</button>
        {% endif %}
    </p>
</div>